from sqlalchemy import create_engine, Column, Integer, String, DateTime, ForeignKey, Text, Float, CheckConstraint
from sqlalchemy.orm import declarative_base, sessionmaker
from datetime import datetime, timedelta

# Database setup
engine = create_engine("sqlite:///mydatabase.db")
Base = declarative_base()

# Impressions table: Stores recommendations generated by RAG (query + LLM explanation)
class Impression(Base):
    __tablename__ = "impressions"
    impression_id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.user_id"), nullable=False)  # Links to users table
    item_id = Column(Integer, ForeignKey("items.item_id"), nullable=False)  # Links to items table
    prompt = Column(Text, nullable=True)  # User query or context (e.g., "Show me action movies")
    explanation = Column(Text, nullable=True)  # LLM-generated reason for recommendation
    timestamp = Column(DateTime, default=datetime.utcnow)

# Feedback table: Stores user feedback on recommendations for evaluation
class Feedback(Base):
    __tablename__ = "feedback"
    feedback_id = Column(Integer, primary_key=True, autoincrement=True)
    impression_id = Column(Integer, ForeignKey("impressions.impression_id"), nullable=False)  # Links to impressions
    feedback_type = Column(String, nullable=True)  # e.g., "like", "dislike", "click"
    rating = Column(Integer, nullable=True)  # e.g., 1-5 star rating
    comment = Column(Text, nullable=True)  # User comments
    clicked = Column(Integer, nullable=True)  # 0/1, aligns with interactions table
    purchased = Column(Integer, nullable=True)  # 0/1, aligns with interactions table
    watch_time = Column(Float, nullable=True)  # Time spent (seconds)
    timestamp = Column(DateTime, default=datetime.utcnow)
    __table_args__ = (
        CheckConstraint("rating IS NULL OR (rating >= 1 AND rating <= 5)", name="check_rating_range"),
        CheckConstraint("feedback_type IN ('like', 'dislike', 'click', 'neutral')", name="check_feedback_type"),
    )

# Create tables (no drop to preserve data)
Base.metadata.create_all(engine)
print("Impressions and Feedback tables created for evaluation!")

# Add sample data for testing (assumes users and items exist)
Session = sessionmaker(bind=engine)
with Session() as session:
    try:
        # Sample Impression: User 1, Item 1 (e.g., a movie)
        impression1 = Impression(
            user_id=1,
            item_id=1,
            prompt="Show me action movies",
            explanation="Recommended because you recently watched 'Mad Max,' a similar action thriller.",
            timestamp=datetime.utcnow() - timedelta(days=2)
        )
        session.add(impression1)
        session.flush()  # Generate impression_id

        # Sample Feedback: Positive feedback for impression1
        feedback1 = Feedback(
            impression_id=impression1.impression_id,
            feedback_type="like",
            rating=4,
            comment="Great recommendation, but I prefer sci-fi.",
            clicked=1,
            purchased=0,
            watch_time=30.5,
            timestamp=datetime.utcnow() - timedelta(days=1)
        )
        session.add(feedback1)

        # Sample Impression: User 2, Item 2 (e.g., sports gear)
        impression2 = Impression(
            user_id=2,
            item_id=2,
            prompt="Find stylish sports gear",
            explanation="Recommended based on your preference for fashionable items and recent sports interactions.",
            timestamp=datetime.utcnow() - timedelta(days=1)
        )
        session.add(impression2)
        session.flush()

        # Sample Feedback: Negative feedback for impression2
        feedback2 = Feedback(
            impression_id=impression2.impression_id,
            feedback_type="dislike",
            rating=2,
            comment="Not my style, too expensive.",
            clicked=1,
            purchased=0,
            watch_time=10.0,
            timestamp=datetime.utcnow()
        )
        session.add(feedback2)

        session.commit()
        print("Sample impressions and feedback added for evaluation!")
    except Exception as e:
        session.rollback()
        print(f"Error adding sample data: {e}. Ensure user_id=1,2 and item_id=1,2 exist in users and items tables.")
    finally:
        session.close()